rrbot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50 
  
  # Position Controllers ---------------------------------------
  joint_base_mid_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_base_mid
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_mid_top_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_mid_top
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_base_mid_position_controller_two:
    type: effort_controllers/JointPositionController
    joint: joint_base_mid_two
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_mid_top_position_controller_two:
    type: effort_controllers/JointPositionController
    joint: joint_mid_top_two
    pid: {p: 100.0, i: 0.01, d: 10.0}
